#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Fri Jul 12 13:08:06 2019 from "C:\Users\Trainer\PycharmProjects\GUI_Examples\DD\Simple_TO-DO_List.wxg"
#

import wx
import wx.grid

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class FirstFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FirstFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 600))
        self.Add = wx.Button(self, wx.ID_ANY, "Add")
        self.inp_msg = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.Quit = wx.Button(self, wx.ID_ANY, "Quit")
        self.grid_1 = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FirstFrame.__set_properties
        self.SetTitle("Simple TO-DO List")
        self.Add.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.Add.SetForegroundColour(wx.Colour(47, 47, 79))
        self.inp_msg.SetFocus()
        self.Quit.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.Quit.SetForegroundColour(wx.Colour(35, 35, 142))
        self.grid_1.CreateGrid(10, 0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FirstFrame.__do_layout
        sizer_1 = wx.WrapSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.Add, 0, wx.ALL, 8)
        sizer_2.Add(self.inp_msg, 0, wx.ALL, 10)
        sizer_2.Add(self.Quit, 0, wx.ALL, 8)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.grid_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class FirstFrame

class SimpleToDoList(wx.App):
    def OnInit(self):
        self.frame = FirstFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class SimpleToDoList

if __name__ == "__main__":
    simple_to_do_list_app = SimpleToDoList(0)
    simple_to_do_list_app.MainLoop()
